### PR TITLE
Update to latest EKS build

### PR DESCRIPTION
**Pull request by dowen12**
*Description of changes:*
Removal of EC2, ECS templates
Updating to helm chart versions rather than ART versions.
Update to latest EKS QS

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bhargavkeshav** [comment]
@dowen12 Why ECS templates were removed from the repositories? Is there any open issue/bug with Artifactory ECS deployment ?

If its moved to some other repo can you please provide us the link?

We are planning to use ECS for our Jfrog Artifactory deployment.

**Comment by vinayagg** [comment]
Hello @bhargavkeshav, I am from JFrog. Can you reach out to support@jfrog.com and we can guide you with a recommended solution.

**Pull request merged**
